import React from "react";

const PictureWall = () => {
  return (
    <div className="container max-w-[1200px] mx-auto py-6">
      <div class="image-wrap">
        <ul class="images">
          <li>
            <img
              src={"/assets/images/wall/1.jpg"}
              alt="test1"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/2.jpg"}
              alt="test2"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/3.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/6.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/4.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/7.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/5.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/9.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/8.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>

          {/*  */}

          <li>
            <img
              src={"/assets/images/wall/1.jpg"}
              alt="test1"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/2.jpg"}
              alt="test2"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/3.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/5.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/9.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/8.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/6.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/4.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/7.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>

          {/*  */}

          <li>
            <img
              src={"/assets/images/wall/1.jpg"}
              alt="test1"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/2.jpg"}
              alt="test2"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/3.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/7.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/6.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/4.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/8.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/5.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/9.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
        </ul>

        <ul class="images">
          <li>
            <img
              src={"/assets/images/wall/4.jpg"}
              alt="test1"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/5.jpg"}
              alt="test2"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/6.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/1.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/9.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/3.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/8.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/2.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/7.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>

          {/*  */}

          <li>
            <img
              src={"/assets/images/wall/4.jpg"}
              alt="test1"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/5.jpg"}
              alt="test2"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/6.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>

          <li>
            <img
              src={"/assets/images/wall/8.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/2.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/7.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>

          <li>
            <img
              src={"/assets/images/wall/1.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/9.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/3.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          {/*  */}

          <li>
            <img
              src={"/assets/images/wall/4.jpg"}
              alt="test1"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/5.jpg"}
              alt="test2"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/6.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/9.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/3.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/1.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/7.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/2.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/8.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
        </ul>

        <ul class="images">
          <li>
            <img
              src={"/assets/images/wall/7.jpg"}
              alt="test1"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/8.jpg"}
              alt="test2"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/9.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/4.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/1.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/5.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/2.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/6.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/3.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>

          {/*  */}

          <li>
            <img
              src={"/assets/images/wall/7.jpg"}
              alt="test1"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/8.jpg"}
              alt="test2"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/9.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>

          <li>
            <img
              src={"/assets/images/wall/2.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/6.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/3.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>

          <li>
            <img
              src={"/assets/images/wall/4.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/1.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/5.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>

          {/*  */}

          <li>
            <img
              src={"/assets/images/wall/7.jpg"}
              alt="test1"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/8.jpg"}
              alt="test2"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/9.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>

          <li>
            <img
              src={"/assets/images/wall/4.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/6.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/2.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>

          <li>
            <img
              src={"/assets/images/wall/5.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/1.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
          <li>
            <img
              src={"/assets/images/wall/3.jpg"}
              alt="test3"
              width="300"
              height="300"
            />
          </li>
        </ul>
      </div>
    </div>
  );
};

export default PictureWall;
